baseURL = "http://localhost:8001/"
languageCode = "en-us"
title = "DA"
description = ""
theme = "lavoz7"
googleAnalytics = "UA-123-45"
paginatePath = '/'

[params]
    mediaDIR = "MEDIA/"

[permalinks]
    posts = "/:slug"
    pages = "/:slug"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = true

[outputs]
  home = ["HTML", "RSS", "JSON"]